// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkH8FMn0MNlTPn4qrptHWa6ts3jrjCed0',
    appId: '1:937662190695:web:5476400497e3896d0d30c2',
    messagingSenderId: '937662190695',
    projectId: 'sport-shop-c1efe',
    authDomain: 'sport-shop-c1efe.firebaseapp.com',
    storageBucket: 'sport-shop-c1efe.appspot.com',
    measurementId: 'G-LL0PTZ4MTN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTU3276FRVZdoQKrIFo-l1J9X-QGpQ7no',
    appId: '1:937662190695:android:ff225bc6ff91fdb70d30c2',
    messagingSenderId: '937662190695',
    projectId: 'sport-shop-c1efe',
    storageBucket: 'sport-shop-c1efe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlZKOxLV6K13KWnbndlnCRTpMPHBn6wxU',
    appId: '1:937662190695:ios:cc79fe9c6b56d9470d30c2',
    messagingSenderId: '937662190695',
    projectId: 'sport-shop-c1efe',
    storageBucket: 'sport-shop-c1efe.appspot.com',
    androidClientId: '937662190695-a7if4b24bkeib5dkngd0dpohb40u0sao.apps.googleusercontent.com',
    iosClientId: '937662190695-7e2rd4s5k6u5sjjopljpjqnsuhtks1tj.apps.googleusercontent.com',
    iosBundleId: 'com.example.sportShopApp',
  );

}